### ISSUE TITLE
Hexahederon mesh fails when number of points in y-direction is greater than 3

### ISSUE THREAD

**Issue by vortexnix** [bhagath555/mesh_VTU_matlab#1]
I tried running `gen_hex_vtu.m` with `py = 5`. The vtu is generated but it fails on loading on Paraview. The issue is likely in computing connectivity. Would you be able help me here. I am trying to understand connectivity procedure but unable to do so.

**Comment by vortexnix** [comment]
I think it was mistake on my side. I closed the issue.

**Comment by bhagath555** [comment]
Actually, there was an error in computing the connectivity for the hexahedron (3d, 8-nodded element) mesh. I corrected it with the latest commit [hex_mesh topology](https://github.com/bhagath555/mesh_VTU/commit/c8ea04f85fa88960b55c3993ad1a3a17280af3e2). Please check it out.
